kind: pipeline
type: docker
name: Backend & web

steps:
  - name: build
    image: golang
    pull: always
    commands:
      - make
      - make package
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: "*.tar.gz"
    when:
      event: tag